<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <Optimize>true</Optimize>
    <TieredPGO>true</TieredPGO>
    <InvariantGlobalization>true</InvariantGlobalization>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <AssemblyName>simcore</AssemblyName>
    <RootNamespace>Nebulytic.Resonance.Sim</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../Assets/Resonance/Runtime/Sim/*.cs" />
    <Compile Include="*.cs" />
  </ItemGroup>
</Project>
